apiVersion: v1
kind: Service
metadata:
  name: spring-cashier-worker-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 6060
    targetPort: 6060
  selector:
    name: spring-cashier-worker
