
version: "3"

services:
  redis:
    image: redis
    platform: linux/amd64
    networks:
      - network
    networks:
      - network
    restart: always
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    networks:
      - network
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: "welcome"
    restart: always
  cashier:
    image: spring-cashier
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "user"
      MYSQL_PASS: "password"
      API_KEY: "2H3fONTa8ugl1IcVS7CjLPnPIS2Hp9dJ"
      API_HOST: "kong:800/api"
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - cashier
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "cashier"
      BACKENDS_PORT: "9090"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

